FROM node:20-slim AS builder
WORKDIR /app

# Increase memory for Next.js build
ENV NODE_OPTIONS="--max_old_space_size=2048"

COPY package*.json ./
RUN npm ci --ignore-scripts

COPY . .

# Pass NEXT_PUBLIC vars at build time
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_WHOP_APP_ID
ARG NEXT_PUBLIC_WHOP_CHECKOUT_URL
ARG NEXT_PUBLIC_APP_URL

ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_WHOP_APP_ID=$NEXT_PUBLIC_WHOP_APP_ID
ENV NEXT_PUBLIC_WHOP_CHECKOUT_URL=$NEXT_PUBLIC_WHOP_CHECKOUT_URL
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL

RUN npm run build

FROM node:20-slim AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0
ENV PORT=3000

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

EXPOSE 3000
CMD ["node", "server.js"]
